name: Continuous Delivery

on:
  workflow_dispatch:
    inputs:
      prNumber:
        description: The number of the PR that is being deployed
        required: true
      ref:
        description: The branch that is being deployed. Should be a branch on the given repository
        required: false
        default: main
      repository:
        description: The {owner}/{repository} that is being deployed.
        required: false
        default: imranbarbhuiya/esbuild-plugins-node-modules-polyfill
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  Publish-Next:
    name: Publish Next to npm
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Project
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          repository: ${{ github.event.inputs.repository || 'imranbarbhuiya/esbuild-plugins-node-modules-polyfill' }}
          ref: ${{ github.event.inputs.ref || 'main' }}
      - name: Use Node.js v24
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: yarn
          registry-url: https://registry.npmjs.org
      - name: Install Dependencies
        run: yarn --immutable
      - name: Bump Version & Publish
        run: |
          TAG=$([[ ${{ github.event_name }} == 'push' ]] && echo 'next' || echo 'pr-${{ github.event.inputs.prNumber }}')
          yarn bump --preid "${TAG}.$(git rev-parse --verify --short HEAD)" --skip-changelog
          npm publish --provenance --tag ${TAG}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Publish-Latest:
    name: Publish Latest to npm
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Project
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Use Node.js v24
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: yarn
          registry-url: https://registry.npmjs.org
      - name: Install Dependencies
        run: yarn --immutable
      - name: Publish
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          npm version "${VERSION}" --no-git-tag-version --allow-same-version
          npm publish --provenance --tag latest
